// <auto-generated />
using Attractions.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Attractions.WebService.Migrations
{
    [DbContext(typeof(AttractionContext))]
    partial class AttractionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Attractions.DomainObjects.Attraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Admission")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameObject")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Admission = "срок действия истек, эксплуатация аттракциона не допускается",
                            Location = "Парк Культуры и отдыха «Сокольники»",
                            NameObject = "DiscO",
                            PeriodA = "04.2019-12.2019"
                        },
                        new
                        {
                            Id = 2L,
                            Admission = "срок действия истек, эксплуатация аттракциона не допускается",
                            Location = "Парк Культуры и отдыха «Измайловский»",
                            NameObject = "Деревенский поезд",
                            PeriodA = "04.2019-12.2019"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
